=== ClaudioDeMeo/CognitiveKitchen/Assets/UI/Data/recipes.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- SCHEMA-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="recipes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="recipe" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="action" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="prefab" type="xs:string"/>
											<xs:attribute name="type">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="movement"/>
														<xs:enumeration value="action"/>
														<xs:enumeration value="wait"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="target" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="title" type="xs:string" use="required"/>
						<xs:attribute name="pot" type="xs:string" use="required"/>
						<xs:attribute name="place" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="hotPlates"/>
									<xs:enumeration value="cuttingBoard"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ClaudioDeMeo/CognitiveKitchen/Assets/UI/Data/recipes.xml
<?xml version="1.0" encoding="utf-8"?>

<recipes xmlns="https://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://www.w3schools.com recipes.xsd">
	<recipe title="Uovo Sodo" pot="Pan" place="hotPlates" cooker="1">
		<action prefab="water" type="movement" target="pot">Metti l'acqua</action>
		<action prefab="egg" type="movement" target="pot">Metti l'uovo</action>
		<action type="action" target="hotPlates" on="true">Accendi Fuoco</action>
		<action type="wait" for="5">Aspetta 5 min</action>
		<action type="action" target="hotPlates" on="false">Spegni Fuoco</action>
	</recipe>
	<recipe title="Pasta al sugo" pot="Saucepan" place="hotPlates" cooker="3">
		<action prefab="water" type="movement" target="pot">Metti l'acqua</action>
		<action type="action" target="hotPlates" on="true">Accendi Fuoco</action>
		<action type="wait" for="2">Fai bollire</action>
		<action prefab="pasta" type="movement" target="pot">Metti la pasta</action>
		<action type="wait" for="5">Aspetta 5 min</action>
		<action prefab="sauce" type="movement" target="pot">Metti il sugo</action>
		<action type="wait" for="2">Aspetta 2 min</action>
		<action type="action" target="hotPlates" on="false">Spegni Fuoco</action>
	</recipe>
</recipes>
